Repository fontplus/web-typography-glossary, pull requests merged in 2019-08, with the labels that each got.

#106 等幅フォントの画像追加
  images/monospaced-font.png
  terms/monospaced-font.md
Labels: figure, in review

#105 7月リリース分の画像修正
  images/family.png
  images/glyph.png
  images/weight.png
  terms/family.md
  terms/glyph.md
  terms/weight.md
Labels: in review

#93 プロポーショナルメトリクス図版作成
  images/proportional-metrics.png
  terms/proportional-metrics.md
Labels: figure, in review

#107 第5回リリース
  .DS_Store
  README.md
  images/family.png
  images/glyph.png
  images/monospaced-font.png
  images/proportional-metrics.png
  images/weight.png
  references.md
  terms/character-encoding.md
  terms/character-reference.md
  terms/family.md
  terms/fout.md
  terms/glyph.md
  terms/monospaced-font.md
  terms/opentype.md
  terms/proportional-metrics.md
  terms/unicode.md
  terms/utf-8.md
  terms/web-font.md
  terms/weight.md
Labels: review needed
